version: '1'
services:
  surveycat-api-nginx:
    image: cntzoufras/api-nginx:latest
    ports:
      - "40000:40000"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - webnet
  surveycat-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: cntzoufras/surveycat-api:latest
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
    environment:
      WWWUSER: 1000
      WWWGROUP: 1000
    networks:
      - webnet
    depends_on:
      - pgsql
      - memcached
      - redis
  pgsql:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'prod-pgsql:/var/lib/postgresql/data'
    networks:
      - webnet
  memcached:
    image: 'memcached:alpine'
    networks:
      - webnet
  redis:
    image: 'redis:alpine'
    volumes:
      - 'prod-redis:/data'
    networks:
      - webnet
networks: # manually created in prod server with network create
  webnet:
    external: true

volumes:
  prod-pgsql:
    driver: local
  prod-redis:
    driver: local
