version: '3.2'
services:
  surveycat-api-apache:
    image: cntzoufras/surveycat-api-apache:1.27
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - IMAGE_VERSION=${IMAGE_VERSION}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
    environment:
      APACHE_SERVER_NAME: "snf-893977.vm.okeanos.grnet.gr"
      WWWUSER: 1000
      WWWGROUP: 1000
    networks:
      - webnet
    ports:
      - "40000:80"
    depends_on:
      - pgsql
      - memcached
      - redis
  #  surveycat-api:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile.prod
  #    image: cntzoufras/surveycat-api:latest
  #    env_file:
  #      - .env
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: '2'
  #    environment:
  #      WWWUSER: 1000
  #      WWWGROUP: 1000
  #    networks:
  #      - webnet
  #    depends_on:
  #      - pgsql
  #      - memcached
  #      - redis
  #    entrypoint: ./entrypoint.sh
  pgsql:
    image: 'postgres:15'
    environment:
      POSTGRES_HOST: '${DB_HOST}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'prod-pgsql:/var/lib/postgresql/data'
    networks:
      - webnet
    ports:
      - "5432:5432"
  memcached:
    image: 'memcached:alpine'
    networks:
      - webnet
  redis:
    image: 'redis:alpine'
    volumes:
      - 'prod-redis:/data'
    networks:
      - webnet
networks: # network create webnet manual
  webnet:
    external: true

volumes:
  prod-pgsql:
    driver: local
  prod-redis:
    driver: local
