name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_ENV: production
  APP_KEY: ${{ secrets.APP_KEY }}
  APP_DEBUG: false
  APP_URL: https://example.com

  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, zip, pcntl
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzip-dev
          sudo docker-compose run --rm composer install
          sudo docker-compose run --rm npm install

      - name: Build Assets
        run: |
          sudo docker-compose run --rm npm run prod

      - name: Run Tests
        run: |
          sudo docker-compose run --rm php vendor/bin/phpunit

      - name: Push Coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests