name: Build, Push, and Deploy Surveycat API Docker Images

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set Docker Host
        env:
          DOCKER_HOST: tcp://snf-893977.vm.okeanos.grnet.gr:2375
        run: echo "Docker Host set successfully."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ls -l ~/.ssh/deploy_key
          cat ~/.ssh/deploy_key

          ssh-keyscan -p 54222 snf-893977.vm.okeanos.grnet.gr >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Stop and pull
        run: |
          ssh -p 54222 -o StrictHostKeyChecking=no 
          -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'cd /var/www/surveycat_front &&
          docker-compose -f docker-compose.prod.yml down && docker rm surveycat_api_surveycat-api_1 && docker-compose -f docker-compose.prod.yml pull'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, pcntl
          coverage: none

      - name: Create .env file
        run: |
          echo "APP_ENV=production" > .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://snf-893977.vm.okeanos.grnet.gr/api" >> .env
          echo "SANCTUM_STATEFUL_DOMAINS=snf-893977.vm.okeanos.grnet.gr" >> .env
          echo "SESSION_DOMAIN=snf-893977.vm.okeanos.grnet.gr" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=api-pgsql-1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Build and push Docker images
        run: |
          echo "${{ secrets.SURVEYCAT_API_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

      - name: Deploy to Production Server
        run: |
          scp -P 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key .env cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr:/var/www/surveycat_api
          ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'cd /var/www/surveycat_api && git pull && docker-compose -f docker-compose.prod.yml up -d'

      - name: Check container status
        run: |
          docker ps

      - name: Run database migrations and seed
        run: |
          docker-compose -f docker-compose.prod.yml exec --tty surveycat-api php artisan migrate:fresh --seed

      - name: Set directories permissions
        run: |
          docker-compose -f docker-compose.prod.yml exec -tty surveycat-api chmod -R 777 storage bootstrap/cache

      - name: Check container logs
        run: |
          docker-compose -f docker-compose.prod.yml logs

      - name: Check containers' status
        run: |
          docker ps

