name: Build, Push, and Deploy Surveycat API Docker Imagesd

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_API_SECRET }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 54222 snf-893977.vm.okeanos.grnet.gr >> ~/.ssh/known_hosts

      - name: Build and Deploy
        run: |
          ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr '
          if ! command -v docker-compose &> /dev/null; then
            curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          fi
          cd /var/www/surveycat_front && git pull && docker-compose -f docker-compose.prod.yml up -d --build'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, pcntl
          coverage: none

      - name: Create .env file
        run: |
          echo "APP_ENV=production" > .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://snf-893977.vm.okeanos.grnet.gr/api" >> .env
          echo "SANCTUM_STATEFUL_DOMAINS=snf-893977.vm.okeanos.grnet.gr" >> .env
          echo "SESSION_DOMAIN=snf-893977.vm.okeanos.grnet.gr" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=api-pgsql-1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          ls -al
          pwd

      - name: Build and push Docker images
        run: |
          echo "${{ secrets.SURVEYCAT_API_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

      - name: Deploy to Production Server
        run: |
          ssh -p 54222 cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'cd /var/www/surveycat_api/app && docker-compose -f docker-compose.prod.yml pull && docker-compose -f docker-compose.prod.yml up -d'

      - name: Check container status
        run: |
          docker ps -a
        continue-on-error: true

      - name: Install Composer dependencies
        run: |
          docker-compose -f docker-compose.prod.yml exec -T surveycat-api composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      - name: Run database migrations and seed
        run: |
          docker-compose -f docker-compose.prod.yml exec --tty surveycat-api php artisan migrate:fresh --seed

      - name: Set directory permissions
        run: |
          docker-compose -f docker-compose.prod.yml exec -T surveycat-api chmod -R 777 storage bootstrap/cache

      - name: Check container logs
        run: |
          docker-compose -f docker-compose.prod.yml logs

      - name: Check container status
        run: |
          docker ps -a

