name: Build and Deploy Docker Imagess

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, pcntl
          coverage: none

      - name: Copy .env from example
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Create .env file
        run: |
          echo "APP_ENV=production" > .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://snf-893977.vm.okeanos.grnet.gr/api" >> .env
          echo "SANCTUM_STATEFUL_DOMAINS=snf-893977.vm.okeanos.grnet.gr" >> .env
          echo "SESSION_DOMAIN=snf-893977.vm.okeanos.grnet.gr" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=api-pgsql-1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          ls -al
          pwd

      #      - name: Copy .env to Production Server
      #        run: scp -p 54222 -i ${{ secrets.SSH_PRIVATE_KEY }} .env snf-893977.vm.okeanos.grnet.gr:/var/www/


      # test
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzip-dev
          composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      - name: Composer Dump Autoload
        run: |
          composer dump-autoload --optimize

      - name: Run Migrations
        run: |
          php artisan migrate:fresh
          php artisan db:seed

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
