name: Surveycat CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, pcntl
          coverage: none

      - name: Create .env.prod file
        run: |
          echo "APP_ENV=production" > .env.prod
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env.prod
          echo "APP_DEBUG=false" >> .env.prod
          echo "APP_URL=https://snf-893977.vm.okeanos.grnet.gr/api" >> .env.prod
          echo "SANCTUM_STATEFUL_DOMAINS=snf-893977.vm.okeanos.grnet.gr >> .env.prod"
          echo "SESSION_DOMAIN=snf-893977.vm.okeanos.grnet.gr >> .env.prod"
          echo "DB_CONNECTION=pgsql" >> .env.prod
          echo "DB_HOST=api-pgsql-1" >> .env.prod
          echo "DB_PORT=5432" >> .env.prod
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env.prod
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env.prod
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.prod

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzip-dev
          composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
          

      - name: Run Migrations
        run: |
          php artisan telescope:install
          php artisan migrate

#      - name: Run Tests
#        run: |
#          sudo docker-compose run --rm php vendor/bin/phpunit
